### ISSUE TITLE
在视觉惯性SLAM系统中的应用

### ISSUE THREAD

**Issue by fightmoney** [MegviiRobot/MegBA#14]
作者您好，请问在ORB-SLAM3和VINS系统里面可以使用这个对BA加速嘛？会不会因为数据量较小导致没有cpu快？MegBA有和g2o的优化速度做过比较嘛，差异有多大？论文似乎未提及g2o的速度，感谢回答。

**Comment by JieRen98** [comment]
Hi,
Thanks for your comments! As far as we know, on very small scale datasets, it would be a better choice to use a decomposition-based linear solver(e.g. CHOLMOD). The decomposition-based linear solvers would have over 10x speedup than the iterative linear solver (e.g. PCG). MegBA does not provide GPU decomposition-based linear solver so far, one reason is that GPU is not suitable for implementing these algorithms. As for your second question, we have not compared to g2o yet, but we released an analytical jacobian computing example.
Notably, the analytical jacobian example is not well optimized, but for reducing GPU memory usage. We will do the optimization in the later version.
Thanks,
Jie
