### ISSUE TITLE
fatal error: nccl.h: No such file or directory

### ISSUE THREAD

**Issue by pshuxue** [MegviiRobot/MegBA#15]
In file included from /home/pengshuxue/Downloads/MegBA/src/algo/lm_algo.cu:15:
/home/pengshuxue/Downloads/MegBA/include/resource/handle_manager.h:11:10: fatal error: nccl.h: No such file or directory
   11 | #include <nccl.h>
      |          ^~~~~~~~
compilation terminated.
CMake Error at lm_algo_CUDA_generated_lm_algo.cu.o.cmake:220 (message):
  Error generating
  /home/pengshuxue/Downloads/MegBA/build/src/algo/CMakeFiles/lm_algo_CUDA.dir//./lm_algo_CUDA_generated_lm_algo.cu.o

make[2]: *** [src/algo/CMakeFiles/lm_algo_CUDA.dir/build.make:65: src/algo/CMakeFiles/lm_algo_CUDA.dir/lm_algo_CUDA_generated_lm_algo.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:340: src/algo/CMakeFiles/lm_algo_CUDA.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Mrs J, what should I do?

**Comment by JieRen98** [comment]
Hi,
Thanks for your comments. MegBA enables distributed features by using [NVIDIA Collective Communications Library (NCCL)](https://developer.nvidia.com/nccl/nccl-download). As mentioned in README, you should install the NCCL library before you compile MegBA.
Best regards,
Jie
