### ISSUE TITLE
dentifier "CUSPARSE_SPMV_ALG_DEFAULT" is undefined

### ISSUE THREAD

**Issue by pshuxue** [MegviiRobot/MegBA#16]
home/pengshuxue/Downloads/MegBA/src/solver/schur_pcg_solver.cu(470): error: identifier "CUSPARSE_SPMV_ALG_DEFAULT" is undefined
          detected during:
            instantiation of "__nv_bool MegBA::<unnamed>::SchurPCGSolverDistributed(const MegBA::SolverOption::SolverOptionPCG &, const std::vector<T *, std::allocator<T *>> &, const std::vector<T *, std::allocator<T *>> &, const std::vector<T *, std::allocator<T *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<T *, std::allocator<T *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<T *, std::allocator<T *>> &, int, int, int, int, const std::vector<int, std::allocator<int>> &, int, int, const std::vector<T *, std::allocator<T *>> &) [with T=double]" 
(658): here
            instantiation of "void MegBA::SchurPCGSolver<T>::solve(const MegBA::BaseLinearSystem<T> &) [with T=double]" 
(661): here

/home/pengshuxue/Downloads/MegBA/src/solver/schur_pcg_solver.cu(201): error: identifier "CUSPARSE_SPMV_ALG_DEFAULT" is undefined
          detected during:
            instantiation of "__nv_bool MegBA::<unnamed>::SchurPCGSolverDistributed(const MegBA::SolverOption::SolverOptionPCG &, const std::vector<T *, std::allocator<T *>> &, const std::vector<T *, std::allocator<T *>> &, const std::vector<T *, std::allocator<T *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<T *, std::allocator<T *>> &, const std::vector<int *, std::allocator<int *>> &, const std::vector<int *, std::allocator<int *>> &, const

**Comment by JieRen98** [comment]
Hi,
Thanks for your comments. This compiling time error is due to the macro name change in the CUDA toolkit. Specifically, in 11.3 or later versions, NVIDIA uses _CUSPARSE_SPMV_ALG_DEFAULT_ as the sparse matrix multiplication flag; but in 11.2 or previous versions, they use _CUSPARSE_MV_ALG_DEFAULT_ as the flag instead. We have fixed this bug by judging the _nvcc_ version and manually defining macro variables.
Best regards,
Jie
