### ISSUE TITLE
sqrt API not exposed 

### ISSUE THREAD

**Issue by xingweiqu** [MegviiRobot/MegBA#19]
Hi ，really appreciate for your amazing work.

I found a bug when i self-implement a vertex, "cuda 700 error". It seems that the sqrt interface not exposed out.

**Comment by JieRen98** [comment]
Hi,
Thanks for your feedback! We fix this bug and provide the API (using auto y = MegBA::math::sqrt(x) where x and y are MegBA::JetVector) in latest update: https://github.com/MegviiRobot/MegBA/pull/18
Best regards,
Jie
