### ISSUE TITLE
Problem building on Windows

### ISSUE THREAD

**Issue by RamadanAhmed** [MegviiRobot/MegBA#23]
Hi,
Thanks for this great contribution, I'm trying to build the repo on windows but I found out that NCCL is not supported on Windows system so I can't build it.
If there is a idea to build library for single gpu without support of NCCL and adding support to windows I would like to contribute for that

**Comment by JieRen98** [comment]
Hi,

Thanks for your comments, we have added a new compilation option (i.e. -DMEGBA_USE_NCCL) in https://github.com/MegviiRobot/MegBA/pull/28. Check the new updated README.md. If you can help with the compilation on Windows, you can fork the repo and create the pull request. We are happy to involve you in MegBA.

Best regards,
Jie

**Comment by RamadanAhmed** [comment]
That's great I will work on it on this weekend

**Comment by JieRen98** [comment]
Look forward to your good news :-)

Jie

**Comment by RamadanAhmed** [comment]
I have finished and it build on windows but there is some major changes in CMakeLists.txt like:
- Added installation and packaging using CPack
- Used Target-based function instead of global ones (for ex. use target_include_directory instead include_directories)
- Used find_package(CUDAToolKit) instead of deprecated find_package(CUDA)
- Added CMakePresets to be easier to automate build and for continuous integration(GitHub/GitLab pipelines)
So Should the pull request be only on the windows part or all the changes that makes building on Windows and Linux consistent ?

**Comment by JieRen98** [comment]
Hi,

Nice job. What's the meaning of "building on Windows and Linux consistent", I guess it may be using the if-else statement in one "CMakeLists.txt" to judge the system and execute the relevant code. If so, I think making it consistent would be better.

Best regards,
Jie

**Comment by JieRen98** [comment]
Hi,

I have merged your pull request. Nice job!

There are several problems in the building stage, check the newly opened pull request (https://github.com/MegviiRobot/MegBA/pull/31). 1) I have difficulty finding thrust, I have to add flag Thrust_DIR to fix it; 2) there is something wrong with the linking of gflags, I modified "examples/CMakeLists.txt"; 3) the header of Eigen3 is not included, I use "include_directories(${EIGEN3_INCLUDE_DIRS})" to fix it temperately. Please polish my pull request, thanks.

Jie
