### ISSUE TITLE
run time error thrust::system::system_error

### ISSUE THREAD

**Issue by khshmt** [MegviiRobot/MegBA#33]
Hi, Thanks a lot for your great contribution.

I got the below error while running the BAL_Double example,

"solving /home/khshmt/cpp_ws/MegBA/data, world_size: 1, max iter: 20, solver_tol: 10, solver_refuse_ratio: 1, solver_max_iter: 50, tau: 1, epsilon1: 1, epsilon2: 1e-10
Start with error: 0, log error: -inf, elapsed 209 ms
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  after reduction step 1: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)"

linux ==>> 20.04
g++ ==>> 9.4.0
cuda ==>> 11.6
GPU ==>> NVIDIA Quadro M6000 
dataset ==>> venice ==>>problem-1778-993923-pre.txt.bz2

cmake configuration and build runs flawless, but i got the above error every time I run knowing It loads all the data(like: num_points, num_cameras, num_observations and so on) from the dataset correctlly.
![Screenshot from 2022-07-07 15-37-16](https://user-images.githubusercontent.com/41961484/177787510-845e291c-8a03-45f5-a00a-29fe084af193.png)

**Comment by JieRen98** [comment]
Hi,

Thanks for your feedback. We have checked your error, the reason is that "problem-1778-993923-pre.txt.bz2" requires about 14GB GPU memory. You can use the example "BAL_Double_analytical", which uses analytical differentiation that reduces almost half of GPU memory usage.

Best regards,
Jie

**Comment by khshmt** [comment]
Thanks a lot Jie, that worked for me 
thanks again and keep the great job
