### ISSUE TITLE
Adding camera-camera edge in case of stereo camera.

### ISSUE THREAD

**Issue by khshmt** [MegviiRobot/MegBA#37]
Hi guys, Thanks for your great contribution.

I want to ask about the possibility of adding an extra type of edge between stereo-camera pairs(camera-camera edge), and if there is a guideline to do that if it is possible

Thanks in advance

**Comment by JieRen98** [comment]
Hi,

The main challenge is our current design assumes that matrices B and C are diagonal blocked. For the camera-camera edge, we should rewrite the Hessian construction and liner solver functions. Currently, we are working on some novel ideas about fast linear solvers. So the feature you mentioned may be supported after several months.

Best regards,
Jie

**Comment by khshmt** [comment]
Thanks for your response Jie, best of luck in the coming work.
