### ISSUE TITLE
Got cudaErrorIllegalAddress error when running the 1778 example 

### ISSUE THREAD

**Issue by GoroYeh-HRI** [MegviiRobot/MegBA#42]
Hi,
I got the following error when running the following command:
![image](https://github.com/MegviiRobot/MegBA/assets/137837175/29d1410d-50d3-48ef-b6f9-808f394e5bae)

I've checked nvidia-smi and seems that I have enough GPU memory.
Could you help me investigate what might be wrong?
Thank you.

**Comment by JieRen98** [comment]
Hi,

I remember 12GB GPU memory is not enough to solve Venice-1778. Possibly, you can use implicit Hessian (https://github.com/MegviiRobot/MegBA/blob/main/examples/BAL_Double_analytical_implicit.cpp). The implicit Hessian builds the Hessian on the fly, which will save a lot of memory.

Best,
Jie

**Comment by GoroYeh-HRI** [comment]
@JieRen98 Thanks for the response!

Unfortunately I was not able to build target `BAL_Double_analytical_implicit` due to the following compile errors:
![image](https://github.com/MegviiRobot/MegBA/assets/137837175/46cc16dc-ced1-442d-9e72-9e6810946175)


Could you tell me what I should do to make this file successfully built?

**Comment by JieRen98** [comment]
Will check it later.

**Comment by JieRen98** [comment]
Greetings,

The bug is solved. Do not forget to use `git submodule update --init` to register the submodule.

If you have further problems, you can re-open this issue or open a new one.

Best,
Jie
