### ISSUE TITLE
feedback of demo

### ISSUE THREAD

**Issue by YZHUA** [MegviiRobot/MegBA#5]
Hello, Your work is pretty well that compared with ceres. I tried your demo of BAL_Float with Venice-52. I noticed that only few iteration of LM sucessed and when I print the deltaXL2 and xL2, the number is very big . 

solving problem-52-64053-pre.txt, world_size: 1, solver iter: 100, solver_tol: 0.01, solver_refuse_ratio: 1, solver_max_iter: 100, tau: 10000, epsilon1: 1, epsilon2: 1e-10
52 64053 347173
0 1 2 3 4 start with error: 1.11521e+07, log error: 7.04736
deltaXL2 = 795.057990 xL2 = 20297.274566
1-th iter error: 967452, log error: 5.98563
deltaXL2 = 641.070984 xL2 = 20457.752299
2-th iter error: 504157, log error: 5.70257
deltaXL2 = 900.042953 xL2 = 20451.053379
3th iter rollbackLM
deltaXL2 = 546.620354 xL2 = 20451.053379
4th iter rollbackLM
deltaXL2 = 284.468891 xL2 = 20451.053379
5-th iter error: 400720, log error: 5.60284
deltaXL2 = 374.414253 xL2 = 20427.049189
6-th iter error: 364873, log error: 5.56214
deltaXL2 = 370.487802 xL2 = 20488.023926
7th iter rollbackLM
deltaXL2 = 2287.042375 xL2 = 20488.023926
8th iter rollbackLM
deltaXL2 = 71488.917241 xL2 = 20488.023926
9-th iter error: 362014, log error: 5.55872
deltaXL2 = 137.477325 xL2 = 74207.259595
10-th iter error: 291625, log error: 5.46482
deltaXL2 = 201.875231 xL2 = 74267.585371
11-th iter error: 277062, log error: 5.44258
deltaXL2 = 181.679374 xL2 = 74428.300552
12-th iter error: 272821, log error: 5.43588
deltaXL2 = 195.595084 xL2 = 74569.198498
13th iter rollbackLM
deltaXL2 = 574978812.009305 xL2 = 74569.198498
14th iter rollbackLM
deltaXL2 = 553295309151825.250000 xL2 = 74569.198498
15th iter rollbackLM
deltaXL2 = 67003134385564172288.000000 xL2 = 74569.198498
16th iter rollbackLM
deltaXL2 = 558190831280728100044800.000000 xL2 = 74569.198498
17th iter rollbackLM
deltaXL2 = 223324689881403556926324736.000000 xL2 = 74569.198498
18th iter rollbackLM
deltaXL2 = 1540883170175477071243902976.000000 xL2 = 74569.198498
19th iter rollbackLM
deltaXL2 = 83242234827980244867088384.000000 xL2 = 74569.198498
20th iter rollbackLM
deltaXL2 = 17566485752858001014784.000000 xL2 = 74569.198498
21th iter rollbackLM
deltaXL2 = 7240292771779925.000000 xL2 = 74569.198498
22th iter rollbackLM
deltaXL2 = 1833498346.973379 xL2 = 74569.198498
23th iter rollbackLM
deltaXL2 = 895261.733858 xL2 = 74569.198498
24th iter rollbackLM
deltaXL2 = 218.569759 xL2 = 74569.198498
25th iter rollbackLM
deltaXL2 = 0.026681 xL2 = 74569.198498
26-th iter error: 272818, log error: 5.43587
deltaXL2 = 0.000000 xL2 = 74569.197054
deltaXL2 <= epsilon2*(xL2+epsilon2) deltaXL2 = 0.000000 xL2 = 74569.197054
solve dur: 3219 ms

**Comment by JieRen98** [comment]
Thanks for your feedback!
We have already noticed the problem that the L2 norm getting very large as you have mentioned in our internal test. The main reason is that for the rejected step in the LM algorithm, MegBA does not recover the constant vector of the linear system correctly. We have fixed it and will release it in the later stable version.
Thanks,
Jie
