### ISSUE TITLE
How to deal with information / correlation matrix in forward()

### ISSUE THREAD

**Issue by cpdm30** [MegviiRobot/MegBA#6]

**Comment by JieRen98** [comment]
Thanks for your feedback!
Currently, the information matrix is not supported. We are currently working on re-constructing MegBA and supporting the analytic Jacobian, which will make MegBA reach higher performance and lower memory cost. The support for the information matrix is on our to-do list, we will get on it as soon as possible.
Thanks,
Jie

**Comment by Went-Liang** [comment]
Thank you for your interest in our project. 
MegBA supports information matrix in the latest release. (Please check PR: [https://github.com/MegviiRobot/MegBA/pull/25](https://github.com/MegviiRobot/MegBA/pull/25))
Specifically, examples/BAL_Double.cpp Line 212 ([https://github.com/MegviiRobot/MegBA/blob/main/examples/BAL_Double.cpp#L212](https://github.com/MegviiRobot/MegBA/blob/main/examples/BAL_Double.cpp#L212)) shows how to implement this feature when adding new edges.
Thanks,
Liang
